name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile and Run Tests
      run: |- name: Compile and Run Tests
  run: |
    # Compile Java files
    javac LoginApp.java LoginAppTest.java

    # Run JUnit tests
    java org.junit.runner.JUnitCore LoginAppTest
